### ISSUE TITLE
NewDefaultLanguages -> NewWithDefaultLanguages

### ISSUE THREAD

**Issue by sun1001sun** [chrisport/go-lang-detector#19]
It would be goog to rename method "NewDefaultLanguages" in README.md
You have "NewDefaultLanguages" instead of "NewWithDefaultLanguages", that cause errror:

`.\lang.go:9: undefined: langdet.NewDefaultLanguages`

**Comment by chrisport** [comment]
done, thanks
Please check also Migration v0.2, the api has changed a little. I will update the Readme asap.
