### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mevartma** [chrisport/go-lang-detector#2]
I have run your test, after i run this command "go get github.com/chrisport/go-lang-detector/langdet":
package main

import (
"fmt"
"github.com/chrisport/go-lang-detector/langdet"
)

func main() {
detector := langdet.NewDefaultDetector()
testString := "do not care about my car"
result := detector.GetClosestLanguage(testString)
fmt.Println(result)
}

and this is the result:
undefined: langdet.NewDefaultDetector

Do i need to install more packages???

**Comment by chrisport** [comment]
Hi, the method "NewDefaultDetector" was renamed to "NewDefaultLanguages" (not very correct, it should be renamed to something more descriptive).

Do you use an IDE? For example Intellij with the Go Plugin has great support for auto complete. This will save you from being stuck in such issues.

**Comment by mevartma** [comment]
I am using vim
