### ISSUE TITLE
Where is the model data?

### ISSUE THREAD

**Issue by DonaldTsang** [chrisport/go-lang-detector#22]
Is the binary blob of https://github.com/chrisport/go-lang-detector/blob/develop/langdet/internal/default_languages.go the model, and if so, why can't it be in plaintext or JSON?

**Comment by chrisport** [comment]
this file is generated using https://github.com/go-bindata/go-bindata

The idea is that it is part of the binary and you do not need to ship a json or plaintext file on the side of your application.
There might be a better approach to this in the meantime, do you have any knowledge about it?

**Comment by DonaldTsang** [comment]
understood, so is it possible to reference what dataset it uses to generate the model?

**Comment by chrisport** [comment]
unfortunately that's not possible, I've set up the defaults some years ago using random texts (mostly from Wikipedia). 

To my understanding it shouldn't make too much of a difference if the dataset was big enough, unless you use texts of a specific kind.

**Comment by DonaldTsang** [comment]
> Wikipedia

Please add this note to the ReadME if you can, thanks for letting me know that you are using Wikipedia.
How do you get and use the data though?

**Comment by chrisport** [comment]
I'm not sure if I understood your question correctly, please let me know if I didn't answer it:
The model is generated from plain text, which I copied into a text file and used the library to analyse it. See more in the Readme under "Analyze new language".

You could analyse different English texts to create a new model for English doing the same. I speculate that this might improve the detection rate if you need to detect similar texts, for example around a specific topic.

**Comment by DonaldTsang** [comment]
@chrisport It would be useful to specify in the documentation where you source the Wikipedia plaintext.

**Comment by chrisport** [comment]
Do you mean, which exact text? or how to do it?
