### ISSUE TITLE
Explanation on the readme

### ISSUE THREAD

**Issue by invasionofsmallcubes** [chrisport/go-lang-detector#25]
Hi,
one thing is not clear to me. Let's say I want to add a language that is not present in the library. One I extracted the text I should call code like in the following snippet.
```
   text_sample := GetTextFromFile("samples/polish.txt")
    french := langdet.Analyze(text_sample, "french")
```

My question is: do I need to do every time I start the program? Isn't there a way to persist the detector?

**Comment by chrisport** [comment]
The result of the `langdet.Analyze` will be a Language object. An easy way to store this, would be to marshal it to json, store it in a file and get the file content and unmarshall it into a Language object again. This works fine if you're ok with deployinh the json along with the code.

In case you don't want this additional json beside your binary, you can convert the json into GO code and compile it into your application. I did so for the default languages, using the library https://github.com/jteeuwen/go-bindata
It seems this library has been archived and probably there are much better approaches now to do so, I'd advise you to look around a bit first. Unfortunately I'm not up-to-date with the GO ecosystem to give you further advise on this.

**Comment by invasionofsmallcubes** [comment]
Thanks for the suggestions!
