### ISSUE TITLE
New detector from reader

### ISSUE THREAD

**Issue by dahankzter** [chrisport/go-lang-detector#6]
It would be good to be able to create a detector from a reader.
The init method that looks for a file path is really difficult to work with in tests etc.

**Comment by chrisport** [comment]
@dahankzter Could you check this merge request? Is it what you have in mind?

https://github.com/chrisport/go-lang-detector/pull/7

**Comment by dahankzter** [comment]
Much nicer thx.
```go
NewWithLanguagesFromReader()
```
 is the new method right?

I remember seeing a
```go
func init(){
// read from file
}
```

Somewhere and while it may not break anything it can be confusing.

**Comment by dahankzter** [comment]
```go
func init() {
	analyzedInput, err := ioutil.ReadFile("default_languages.json")
	if err != nil {
		fmt.Println("go-lang-detector/langdet: No default languages loaded. default_languages.json not present")
		return
	}
	err = json.Unmarshal(analyzedInput, &defaultLanguages)
	if err != nil {
		fmt.Println("go-lang-detector/langdet: Could not unmarshall default languages from default_languages.json")
		return
	}
}
```

**Comment by dahankzter** [comment]
I understand wanting to make a default detector available. It is a trade off I guess.

**Comment by chrisport** [comment]
defaultLanguage is initialized in init() method. I added two methods, one to change defaultLanguage from Reader, the other to create a new Detector with language-map from Reader.

you can use InitWithDefaultFromReader(reader io.Reader) if you use the DefaultDetector
or NewWithLanguagesFromReader(reader io.Reader) if you construct a new Detector

**Comment by dahankzter** [comment]
Looks good!

**Comment by chrisport** [comment]
Alright then, I've merged it to develop :)
