### ISSUE TITLE
Restructure package?

### ISSUE THREAD

**Issue by Xeoncross** [chrisport/go-lang-detector#9]
This repository seems to be structured incorrectly. Rather than having the examples in an `examples/` folder they seem to be the root level and the actual package is `github.com/chrisport/go-lang-detector/langdet`. In addition, the package has an `init()` call that always fails because the default_languages.json file isn't in the package folder.

```
package main

import (
	"fmt"
	"github.com/chrisport/go-lang-detector/langdet"
)

func main() {

	strs := []string{
		"do not care about quantity",
		"ont permis d'identifier",
		"English 简体中文",
	}

	filepath := "...    ...go/src/github.com/chrisport/go-lang-detector/default_languages.json"
	langdet.InitWithDefault(filepath)
	detector := langdet.NewDefaultLanguages()

	for _, s := range strs {
		fmt.Println(s)
		fmt.Println(detector.GetLanguages(s))
	}

}
```

Running this code gives the following output:

```
$ go run lang.go
go-lang-detector/langdet: No default languages loaded. default_languages.json not present
do not care about quantity
[{english 90} {french 75} {german 50} {turkish 44} {hebrew 19} {arabic 1} {russian 0}]
ont permis d'identifier
[{french 86} {english 80} {german 71} {turkish 54} {hebrew 33} {arabic 2} {russian 0}]
English 简体中文
[{english 48} {german 37} {french 29} {turkish 22} {hebrew 16} {arabic 2} {russian 0}]
```

**Comment by chrisport** [comment]
Right, the package is github.com/chrisport/go-lang-detector/langdet, there shouldn't be any problem, 'go get' will resolve it. An example-folder would be nicer, you are right.
The init() method doesn't fail, it just prints a warning that no DefaultLanguage file was present. I added this message so developers don't assume that default languages are present. Maybe we can improve the message to make clear that it is not an error, something like "go-lang-detector/langdet: info - No default languages loaded, since no default_languages.json present. Please add languages manually."
Feel free to make pull request, otherwise I will apply these things later.

**Comment by Xeoncross** [comment]
What if the `default_languages.json` was just packaged up as part of the lib https://github.com/jteeuwen/go-bindata? Then it could included as needed when no other source language files were loaded. In fact, we can just wrap the JSON in a string and add a package header and be done with it.

**Comment by chrisport** [comment]
sorry for my late response. The problem about this is that the default_language file is 1.6MB. Now we can debate if that's a big number or not. 
Maybe we can have it in bound to a separate package which sets the default language in an init and can be imported manually as an underscore import.

**Comment by jalkanen** [comment]
Just as a datapoint, the new "dep" tool (which hopefully should become the official go dependency tool) fails with

```
% dep ensure github.com/chrisport/go-lang-detector/langdet
dependency path github.com/chrisport/go-lang-detector/langdet is not a project root, try github.com/chrisport/go-lang-detector instead
```

Unsure whether this is an issue with dep or with this repo, but nevertheless a more standard layout would be appreciated.

Perhaps a separate repository with more language samples and default_languages.json which could be trivially git clone'd as a submodule or downloaded as a tarball and extracted into a project?

**Comment by chrisport** [comment]
That sounds very reasonable. I will look into restructuring it soon. In the meantime if anybody has time, please feel free to do it.

**Comment by chrisport** [comment]
Following [vgo](https://research.swtch.com/vgo) for possible v1 release under standard structure.
For more information about VGO, watch ['Opening keynote: Go with Versions - GopherConSG 2018
'](https://www.youtube.com/watch?v=F8nrpe0XWRg)
